### ISSUE TITLE
Add a question pane to view question

### ISSUE THREAD

**Issue by starwiz-7** [starwiz-7/codestream#19]
**Is your feature request related to a problem? Please describe.**
Add a pane for users to fetch questions in the codestream

**Describe the solution you'd like**
Use **Chakra-UI's drawer** component to allow the user to submit a link to a question and then view the question in the same place.
The API call to the backend will post the URL and will receive the question HTML as the response

**Additional context**
The response will be received from the server.
The issue to build scraper - 
#18

**Comment by GhostOrder28** [comment]
Hello, I would like to help, however can you clarify a thing for me?

> ...to allow the user to submit a link to a question

Did you mean that there should be a link that when clicked a new pane should appear in which the user can write their questions? and I'm assuming that submitted questions should be visible for all users, am I right?

**Comment by starwiz-7** [comment]
Hi @GhostOrder28 , there should be a button on the page when clicked should open a drawer. Inside the drawer we will have an input box and a submit button. User can paste the question link in the input box and then submit. Once submitted, an API call will be made to backend which in turn will send response with the scraped question which would be rendered inside the drawer itself in the remaining space.

Yes, the question in that space should be visible for all users in the room!
